"""
De-embedding con scikit-rf — múltiples modelos de fixture

Modelos de fixture (fixture_model):
  'pi'          — Koolen (BCTM 1991): sustraccion Y luego Z. Requiere OPEN + SHORT.
                  Fixture: Yp/2 || Z_series || Yp/2
  't'           — Dual de Koolen: sustraccion Z luego Y. Requiere OPEN + SHORT.
                  Fixture: Z_a -|- Y_shunt -|- Z_b
  'series_only' — Solo serie: Z_int = Z(Y_dut) - Z(Y_short). Solo SHORT.
  'shunt_only'  — Solo shunt: Y_corr = Y_dut - Y_open; Z_int = pinv(Y_corr)[0,0]. Solo OPEN.

Topología del DUT (reconstrucción S-param):
  'shunt'  — DUT entre señal y masa (shunt-through)
  'series' — DUT en serie entre los dos puertos
"""
from __future__ import annotations

import io
import os
import base64
import tempfile
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import skrf as rf

# ─────────────────────────────────────────────────────────────────────────────
# Utilidades internas
# ─────────────────────────────────────────────────────────────────────────────

def _load_network(data: bytes, hint: str = '') -> rf.Network:
    """
    Carga un rf.Network desde bytes en memoria usando un fichero temporal.
    scikit-rf detecta el formato por extensión, así que preservamos el sufijo
    del nombre original (hint).
    """
    ext = '.s2p'
    lower = hint.lower()
    if lower.endswith('.s1p'):
        ext = '.s1p'
    elif lower.endswith('.s2p'):
        ext = '.s2p'

    with tempfile.NamedTemporaryFile(suffix=ext, delete=False) as tmp:
        tmp.write(data)
        tmp_path = tmp.name
    try:
        return rf.Network(tmp_path)
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass


def _fig_to_b64(fig: plt.Figure) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format='png', dpi=130, bbox_inches='tight')
    buf.seek(0)
    return base64.b64encode(buf.read()).decode()


def _to_2port(ntwk: rf.Network, freq: rf.Frequency, z0: float) -> rf.Network:
    """
    Asegura red 2×2. Si viene de calibración SOL (1 puerto), reconstuye
    la simetría: S22 = S11, S21 = S12 = sqrt(1 - |S11|²) aproximado → 0
    (fixture simétrico con S12 ≈ S21 medido, o sin datos fuera de S11).
    """
    N = len(freq.f)
    s = ntwk.s
    if s.shape[1] == 2:
        return ntwk
    # 1-puerto → 2-puerto simétrico
    s2 = np.zeros((N, 2, 2), dtype=complex)
    s2[:, 0, 0] = s[:, 0, 0]
    s2[:, 1, 1] = s[:, 0, 0]   # S22 = S11 (fixture simétrico)
    # S21, S12 se dejan a 0 — no hay información de transmisión en S11 solo
    return rf.Network(frequency=freq, s=s2, z0=z0)


def _write_touchstone(f_hz: np.ndarray, S: np.ndarray, z0: float,
                      fixture_model: str = '') -> str:
    """
    Genera cadena Touchstone .s2p  (# Hz S RI R z0)
    S shape: (N, 2, 2) complejo.
    """
    lines = [
        f"! De-embedded network — fixture model: {fixture_model}",
        f"! Generated by RF Tool Suite · De-embedding tool",
        f"# Hz S RI R {z0:.1f}",
    ]
    for i, fi in enumerate(f_hz):
        s = S[i]
        row = (
            f"{fi:.6e}  "
            f"{s[0,0].real:.10e} {s[0,0].imag:.10e}  "
            f"{s[1,0].real:.10e} {s[1,0].imag:.10e}  "
            f"{s[0,1].real:.10e} {s[0,1].imag:.10e}  "
            f"{s[1,1].real:.10e} {s[1,1].imag:.10e}"
        )
        lines.append(row)
    return "\n".join(lines) + "\n"


# ─────────────────────────────────────────────────────────────────────────────
# Función principal
# ─────────────────────────────────────────────────────────────────────────────

def run_deembedding(
    dut_bytes:     bytes,
    open_bytes:    bytes | None,
    short_bytes:   bytes | None,
    z0:            float = 50.0,
    topology:      str   = 'shunt',
    fixture_model: str   = 'pi',
    dut_hint:      str   = 'dut.s2p',
    open_hint:     str   = 'open.s2p',
    short_hint:    str   = 'short.s2p',
) -> dict:
    """
    Aplica de-embedding y devuelve touchstone_content, summary, plots, warnings.

    fixture_model : 'pi' | 't' | 'series_only' | 'shunt_only'
    topology      : 'shunt' | 'series'  (conexión del DUT para reconstruir S-params)
    """
    needs_open  = fixture_model in ('pi', 't', 'shunt_only')
    needs_short = fixture_model in ('pi', 't', 'series_only')

    if needs_open and open_bytes is None:
        raise ValueError(f"El modelo de fixture '{fixture_model}' requiere la medida OPEN.")
    if needs_short and short_bytes is None:
        raise ValueError(f"El modelo de fixture '{fixture_model}' requiere la medida SHORT.")

    # ── 1. Carga ──────────────────────────────────────────────────────────────
    ntwk_dut   = _load_network(dut_bytes,   dut_hint)
    ntwk_open  = _load_network(open_bytes,  open_hint)  if needs_open  else None
    ntwk_short = _load_network(short_bytes, short_hint) if needs_short else None

    # ── 1b. Validación de coherencia de frecuencias ───────────────────────────
    freq_warnings: list[str] = []
    f_d = ntwk_dut.f
    for ntwk_ref, lbl in [(ntwk_open, 'OPEN'), (ntwk_short, 'SHORT')]:
        if ntwk_ref is None:
            continue
        f_r = ntwk_ref.f
        if len(f_d) != len(f_r):
            raise ValueError(
                f"DUT y {lbl} tienen distinto número de puntos: DUT={len(f_d)}, {lbl}={len(f_r)}."
            )
        max_rel = float(np.max(np.abs(f_d - f_r) / np.maximum(np.abs(f_d), 1.0)))
        if max_rel > 1e-3:
            freq_warnings.append(
                f"DUT vs {lbl}: diferencia relativa máxima de frecuencia {max_rel*100:.2f} %. "
                f"Mide todos con los mismos parámetros en el NanoVNA."
            )

    freq = ntwk_dut.frequency
    f_hz = freq.f
    N    = len(f_hz)

    # Imponer Z0 y convertir a 2-puerto
    for ntwk in filter(None, (ntwk_dut, ntwk_open, ntwk_short)):
        ntwk.z0 = float(z0)
    ntwk_dut   = _to_2port(ntwk_dut,   freq, z0)
    if ntwk_open  is not None: ntwk_open  = _to_2port(ntwk_open,  freq, z0)
    if ntwk_short is not None: ntwk_short = _to_2port(ntwk_short, freq, z0)

    # ── 2–3. De-embedding según modelo de fixture ─────────────────────────────
    Y_dut   = ntwk_dut.y
    Y_open  = ntwk_open.y  if ntwk_open  is not None else None
    Y_short = ntwk_short.y if ntwk_short is not None else None

    Z_int = np.zeros(N, dtype=complex)

    if fixture_model == 'pi':
        # Koolen 1991: Yp/2 || Z_series || Yp/2
        # Paso 1 (Y): Y_corr = Y_dut − Y_open  → elimina shunt
        # Paso 2 (Z): Z_int  = Z(Y_corr_dut) − Z(Y_corr_short)  → elimina serie
        Y_dut_c   = Y_dut   - Y_open
        Y_short_c = Y_short - Y_open
        for i in range(N):
            Zd = np.linalg.pinv(Y_dut_c[i])
            Zs = np.linalg.pinv(Y_short_c[i])
            Z_int[i] = (Zd - Zs)[0, 0]

    elif fixture_model == 't':
        # Dual de Koolen: Za −|− Y_shunt −|− Zb
        # Paso 1 (Z): Z_corr = Z_dut − Z_short  → elimina serie
        # Paso 2 (Y): Y_int  = Y(Z_corr_dut) − Y(Z_corr_open)  → elimina shunt
        for i in range(N):
            Zd_mat = np.linalg.pinv(Y_dut[i])
            Zs_mat = np.linalg.pinv(Y_short[i])
            Zo_mat = np.linalg.pinv(Y_open[i])
            Z_corr_dut  = Zd_mat - Zs_mat
            Z_corr_open = Zo_mat - Zs_mat
            Y_corr_dut  = np.linalg.pinv(Z_corr_dut)
            Y_corr_open = np.linalg.pinv(Z_corr_open)
            Y_int = Y_corr_dut - Y_corr_open
            Z_int[i] = np.linalg.pinv(Y_int)[0, 0]

    elif fixture_model == 'series_only':
        # Solo parásitos serie (trazas inductivas, sin capacidad de pad)
        # Requiere solo SHORT
        for i in range(N):
            Zd = np.linalg.pinv(Y_dut[i])
            Zs = np.linalg.pinv(Y_short[i])
            Z_int[i] = (Zd - Zs)[0, 0]

    elif fixture_model == 'shunt_only':
        # Solo parásitos shunt (capacidad de pad, sin inductancia de traza)
        # Requiere solo OPEN
        Y_corr = Y_dut - Y_open
        for i in range(N):
            Z_int[i] = np.linalg.pinv(Y_corr[i])[0, 0]

    else:
        raise ValueError(f"fixture_model desconocido: '{fixture_model}'. "
                         f"Usa 'pi', 't', 'series_only' o 'shunt_only'.")

    # ── 4. Reconstruir S del DUT intrínseco ───────────────────────────────────
    S_out = np.zeros((N, 2, 2), dtype=complex)
    if topology == 'series':
        # Elemento serie Z entre P1 y P2:
        #   S11 = S22 = Z / (Z + 2·Z0)
        #   S21 = S12 = 2·Z0 / (Z + 2·Z0)
        for i in range(N):
            Z = Z_int[i]
            denom = Z + 2 * z0
            S_out[i, 0, 0] = S_out[i, 1, 1] = Z / denom
            S_out[i, 0, 1] = S_out[i, 1, 0] = 2 * z0 / denom
    else:
        # Elemento shunt Z entre señal y masa (medición shunt-through):
        # ABCD = [[1, 0], [1/Z, 1]]  →  fórmulas directas:
        #   S11 = S22 = -Z0 / (2·Z + Z0)
        #   S21 = S12 =  2Z / (2·Z + Z0)
        # OJO: S11 es NEGATIVO para un shunt puro — la Y-matrix clásica
        # [[1/Z,-1/Z],[-1/Z,1/Z]] daba signo incorrecto en S11.
        for i in range(N):
            Z = Z_int[i]
            denom = 2 * Z + z0
            S_out[i, 0, 0] = S_out[i, 1, 1] = -z0 / denom
            S_out[i, 0, 1] = S_out[i, 1, 0] =  2 * Z / denom

    # ── 5. Touchstone ─────────────────────────────────────────────────────────
    touchstone = _write_touchstone(f_hz, S_out, z0, fixture_model)

    # ── 6. Parámetros de diagnóstico ──────────────────────────────────────────
    Z_mag = np.abs(Z_int)
    Z_im  = Z_int.imag

    sc = np.where(np.diff(np.sign(Z_im)))[0]
    srf_hz = None
    if len(sc):
        i0 = sc[0]
        srf_hz = float(
            f_hz[i0] + (f_hz[i0+1] - f_hz[i0]) * (-Z_im[i0]) / (Z_im[i0+1] - Z_im[i0])
        )
    else:
        srf_hz = float(f_hz[np.argmin(Z_mag)])

    c_est = None
    mask_c = (f_hz >= 1e6) & (f_hz <= 5e6) & (Z_im < 0)
    if mask_c.sum() >= 3:
        c_est = float(np.median(-1.0 / (2 * np.pi * f_hz[mask_c] * Z_im[mask_c])))

    summary = {
        "n_points": N,
        "fmin_mhz": float(f_hz[0] / 1e6),
        "fmax_mhz": float(f_hz[-1] / 1e6),
        "srf_mhz":  float(srf_hz / 1e6) if srf_hz else None,
        "c_est_nf": float(c_est * 1e9)  if c_est  else None,
        "topology":      topology,
        "fixture_model": fixture_model,
        "z0":            z0,
    }

    # ── 7. Gráficas ───────────────────────────────────────────────────────────
    plots = []
    f_MHz = f_hz / 1e6
    plt.rcParams.update({'font.size': 9})

    # — Plot 1: |Z| y Re/Im(Z) de-embeddado —
    fig1, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4.5))
    fig1.suptitle("Impedancia intrínseca (de-embeddada)", fontsize=11, fontweight='bold')

    ax1.semilogy(f_MHz, Z_mag, color='steelblue', lw=1.5, label='|Z| de-embeddada')
    if srf_hz:
        ax1.axvline(srf_hz/1e6, color='orange', ls='--', lw=1.0, label=f'SRF = {srf_hz/1e6:.1f} MHz')
    ax1.set(xlabel='Frecuencia (MHz)', ylabel='|Z| (Ω)', xlim=[f_MHz[0], f_MHz[-1]])
    ax1.legend(fontsize=8); ax1.grid(True, which='both', ls=':', alpha=0.5)

    ax2.plot(f_MHz, Z_int.real, color='steelblue', lw=1.2, label='Re(Z)')
    ax2.plot(f_MHz, Z_int.imag, color='coral',     lw=1.2, label='Im(Z)')
    ax2.axhline(0, color='k', lw=0.5)
    if srf_hz:
        ax2.axvline(srf_hz/1e6, color='orange', ls='--', lw=1.0, label=f'SRF = {srf_hz/1e6:.1f} MHz')
    ax2.set(xlabel='Frecuencia (MHz)', ylabel='Z (Ω)', xlim=[f_MHz[0], f_MHz[-1]])
    ax2.legend(fontsize=8); ax2.grid(True, ls=':', alpha=0.5)
    plt.tight_layout()
    plots.append({"id": "impedance", "title": "Impedancia de-embeddada", "image": _fig_to_b64(fig1)})
    plt.close(fig1)

    # — Plot 2: S21 RAW vs de-embeddado —
    fig2, ax3 = plt.subplots(figsize=(10, 4.5))
    s21_raw_db   = 20 * np.log10(np.maximum(np.abs(ntwk_dut.s[:, 1, 0]), 1e-15))
    s21_deemb_db = 20 * np.log10(np.maximum(np.abs(S_out[:, 1, 0]), 1e-15))
    ax3.plot(f_MHz, s21_raw_db,   color='steelblue', lw=1.2, label='S21 DUT raw')
    ax3.plot(f_MHz, s21_deemb_db, color='tomato',    lw=1.5, ls='--', label='S21 de-embeddado')
    ax3.set(xlabel='Frecuencia (MHz)', ylabel='S21 (dB)',
            title='S21 RAW vs De-embeddado', xlim=[f_MHz[0], f_MHz[-1]])
    ax3.legend(fontsize=9); ax3.grid(True, ls=':', alpha=0.5)
    plt.tight_layout()
    plots.append({"id": "s21", "title": "S21 RAW vs De-embeddado", "image": _fig_to_b64(fig2)})
    plt.close(fig2)

    # — Plot 3: S11 y S21 de los tres fixtures —
    fig3, (ax4, ax5) = plt.subplots(1, 2, figsize=(12, 4.5))
    fig3.suptitle("Señales brutas: DUT, OPEN, SHORT", fontsize=11, fontweight='bold')
    for ntwk_r, lbl, col in [
        (ntwk_dut,   'DUT',   'steelblue'),
        (ntwk_open,  'OPEN',  'green'),
        (ntwk_short, 'SHORT', 'red'),
    ]:
        if ntwk_r is None:
            continue
        s11_db = 20 * np.log10(np.maximum(np.abs(ntwk_r.s[:, 0, 0]), 1e-15))
        s21_db = 20 * np.log10(np.maximum(np.abs(ntwk_r.s[:, 1, 0]), 1e-15))
        ax4.plot(f_MHz, s11_db, color=col, lw=1.2, label=lbl)
        ax5.plot(f_MHz, s21_db, color=col, lw=1.2, label=lbl)
    ax4.set(xlabel='Frecuencia (MHz)', ylabel='S11 (dB)', title='S11 raw', xlim=[f_MHz[0], f_MHz[-1]])
    ax5.set(xlabel='Frecuencia (MHz)', ylabel='S21 (dB)', title='S21 raw', xlim=[f_MHz[0], f_MHz[-1]])
    for ax in (ax4, ax5):
        ax.legend(fontsize=8); ax.grid(True, ls=':', alpha=0.5)
    plt.tight_layout()
    plots.append({"id": "raw", "title": "Señales brutas (DUT / OPEN / SHORT)", "image": _fig_to_b64(fig3)})
    plt.close(fig3)

    return {
        "touchstone_content": touchstone,
        "summary": summary,
        "plots": plots,
        "warnings": freq_warnings,
    }
