import pynanovna
import numpy as np
import io
import base64
import matplotlib
import time
matplotlib.use('Agg')
import matplotlib.pyplot as plt

def get_vna_connection():
    try:
        vna = pynanovna.VNA()
        # Give it a moment to initialize the serial connection
        time.sleep(0.5)
        if not vna.is_connected():
            # Try one more time after a longer delay
            time.sleep(1.0)
            if not vna.is_connected():
                raise ConnectionError("NanoVNA not detected. check USB connection and drivers.")
        return vna
    except Exception as e:
        raise ConnectionError(f"Failed to connect to NanoVNA: {str(e)}")

def calibrate_step(vna, step: str):
    # step: 'short', 'open', 'load', 'isolation', 'through'
    vna.calibration_step(step)
    return {"status": f"Step {step} completed"}

def finalize_calibration(vna, save_path=None):
    try:
        print("--- Finalizing calibration in hardware ---")
        vna.calibrate()
        
        # Save to a temporary file to read its content
        temp_filename = f"temp_cal_{int(time.time())}.cal"
        vna.save_calibration(temp_filename)
        
        import os
        if os.path.exists(temp_filename):
            with open(temp_filename, "rb") as f:
                content = f.read()
            
            import base64
            content_base64 = base64.b64encode(content).decode('utf-8')
            
            # Clean up temp file
            os.remove(temp_filename)
            
            return {
                "status": "success",
                "message": "Calibración generada correctamente",
                "file_content": content_base64,
                "suggested_name": "calibracion_nanovna.cal"
            }
        else:
            return {"status": "error", "message": "No se pudo generar el archivo de calibración en el servidor."}
            
    except Exception as e:
        import traceback
        traceback.print_exc()
        return {"status": "error", "message": f"Error en hardware: {str(e)}"}

def process_sweep(vna):
    stream = vna.stream()
    s11, s21, freqs = next(stream)
    
    # Process and return data
    s11_db = 20 * np.log10(np.maximum(np.abs(s11), 1e-12))
    s21_db = 20 * np.log10(np.maximum(np.abs(s21), 1e-12))
    
    plt.figure(figsize=(10, 5))
    plt.plot(freqs/1e6, s11_db, label="S11 (dB)")
    plt.plot(freqs/1e6, s21_db, label="S21 (dB)")
    plt.title("VNA Live Measurement")
    plt.xlabel("Frequency (MHz)")
    plt.ylabel("Magnitude (dB)")
    plt.grid(True, alpha=0.3)
    plt.legend()
    
    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    buf.seek(0)
    plot_base64 = base64.b64encode(buf.read()).decode('utf-8')
    plt.close()
    
    # Generate S2P content
    s2p_lines = ["! Touchstone file generated by RF Tool Suite", "# Hz S RI R 50"]
    for i, f in enumerate(freqs):
        re11, im11 = np.real(s11[i]), np.imag(s11[i])
        re21, im21 = np.real(s21[i]), np.imag(s21[i])
        s2p_lines.append(f"{f} {re11} {im11} {re21} {im21} {re21} {im21} {re11} {im11}")
    
    s2p_content = "\n".join(s2p_lines)

    return {
        "freqs": freqs.tolist(),
        "s11_real": np.real(s11).tolist(),
        "s11_imag": np.imag(s11).tolist(),
        "s21_real": np.real(s21).tolist(),
        "s21_imag": np.imag(s21).tolist(),
        "plot": plot_base64,
        "s2p_content": s2p_content
    }

def run_sweep(start_hz, stop_hz, points, calibration_path=None):
    vna = get_vna_connection()
    if calibration_path:
        vna.load_calibration(calibration_path)
    vna.set_sweep(start_hz, stop_hz, points)
    return process_sweep(vna)